-- create database and ensure rest of script executes in it

CREATE myDatabase;

USE myDatabase;

CREATE TABLE Customers (
	CustID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	CustFName VARCHAR(20) NOT NULL,
	CustLName VARCHAR(20) NOT NULL,
	CustPhoneNum CHAR(10) NOT NULL,
	CustAddress VARCHAR(50) NOT NULL,
	CustCreditLimit DECIMAL(10,2) NULL,
	CustBalance DECIMAL(10,2) NULL
);

CREATE TABLE Orders (
	OrderID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	CustID INT NOT NULL REFERENCES Customers(CustID),
	OrderDateTime DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
	OrderAmountPaid DECIMAL(10,2) NOT NULL DEFAULT 0,
	OrderDelivered BIT NOT NULL DEFAULT 0
);

CREATE TABLE OrderItems (
	OrderID INT NOT NULL REFERENCES Orders(OrderID),
	CustID INT NOT NULL REFERENCES Customers(CustID),
	OIQuantity INT NOT NULL DEFAULT 1, 
	OIFulfilled BIT NOT NULL DEFAULT 0,
	PRIMARY KEY(OrderID, CustID)
);

CREATE TABLE Parts (
	PartID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	PartPrice DECIMAL(10,2) NOT NULL,
	PartName VARCHAR(40) NOT NULL,
	PartDescription VARCHAR(120) NULL,
	PartLeadTimeDays INT NULL
);
